#if !canImport(ObjectiveC)
import XCTest

extension SemanticVersionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SemanticVersionTests = [
        ("test_allowLeadingZeroes", test_allowLeadingZeroes),
        ("test_asciiAlnumHyphen", test_asciiAlnumHyphen),
        ("test_codable", test_codable),
        ("test_comparators_and_api_stability", test_comparators_and_api_stability),
        ("test_description", test_description),
        ("test_init", test_init),
        ("test_instanceEquality", test_instanceEquality),
        ("test_LosslessStringConvertible", test_LosslessStringConvertible),
        ("test_noLeadingZeroes", test_noLeadingZeroes),
        ("test_nonEmptyIdentifiers", test_nonEmptyIdentifiers),
        ("test_precedence", test_precedence),
        ("test_ranges", test_ranges),
        ("test_semverRule_11_precedence", test_semverRule_11_precedence),
        ("test_semverRule_9_preRelease", test_semverRule_9_preRelease),
        ("test_sort", test_sort),
        ("testHashable", testHashable),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SemanticVersionTests.__allTests__SemanticVersionTests),
    ]
}
#endif
